----------------------------------------------------
-- Scenario 1 : Audit Balance Changes
----------------------------------------------------

CREATE TABLE AccountAudit
(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountID NUMBER,
    OldBalance NUMBER,
    NewBalance NUMBER,
    ChangeDate DATE
);

CREATE OR REPLACE TRIGGER AuditBalanceChanges

AFTER UPDATE OF Balance
ON Accounts

FOR EACH ROW

BEGIN

    INSERT INTO AccountAudit
    (
        AccountID,
        OldBalance,
        NewBalance,
        ChangeDate
    )
    VALUES
    (
        :OLD.AccountID,
        :OLD.Balance,
        :NEW.Balance,
        SYSDATE
    );

END;
/

----------------------------------------------------
-- Test Case
----------------------------------------------------

UPDATE Accounts
SET Balance = 15000
WHERE AccountID = 101;

COMMIT;

----------------------------------------------------
-- Verify Output
----------------------------------------------------

SELECT *
FROM AccountAudit
ORDER BY AuditID;

----------------------------------------------------
-- Scenario 2 : Prevent Negative Balance
----------------------------------------------------

CREATE OR REPLACE TRIGGER PreventNegativeBalance

BEFORE UPDATE OF Balance
ON Accounts

FOR EACH ROW

BEGIN

    IF :NEW.Balance < 0 THEN

        RAISE_APPLICATION_ERROR
        (
            -20001,
            'Balance cannot be negative.'
        );

    END IF;

END;
/

----------------------------------------------------
-- Test Case
----------------------------------------------------

UPDATE Accounts
SET Balance = -500
WHERE AccountID = 101;

----------------------------------------------------
-- Verify Output
----------------------------------------------------

SELECT *
FROM Accounts
WHERE AccountID = 101;

----------------------------------------------------
-- Scenario 3 : Customer Update Audit
----------------------------------------------------

CREATE TABLE CustomerAudit
(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    CustomerName VARCHAR2(50),
    ActionPerformed VARCHAR2(20),
    ActionDate DATE
);

CREATE OR REPLACE TRIGGER AuditCustomerUpdates

AFTER UPDATE
ON Customers

FOR EACH ROW

BEGIN

    INSERT INTO CustomerAudit
    (
        CustomerID,
        CustomerName,
        ActionPerformed,
        ActionDate
    )
    VALUES
    (
        :NEW.CustomerID,
        :NEW.Name,
        'UPDATED',
        SYSDATE
    );

END;
/

----------------------------------------------------
-- Test Case
----------------------------------------------------

UPDATE Customers
SET Balance = 17000
WHERE CustomerID = 102;

COMMIT;

----------------------------------------------------
-- Verify Output
----------------------------------------------------

SELECT *
FROM CustomerAudit
ORDER BY AuditID;